### ISSUE TITLE
Why frustratingly?

### ISSUE THREAD

**Issue by ykk648** [wjf5203/SeqFormer#1]
Frustratingly Simple Few-Shot Object Detection
Frustratingly Simple Domain Generalization via Image Stylization

I‘m just wondering what's the meaning of 'Frustratingly'...

**Comment by chrisjuniorli** [comment]
Investigating in a new area that many previous sota solutions are complicated, then finding out a simple baseline beats sota easily makes stoa solutions feel frustrating. Just my 2 cents :)

**Comment by ykk648** [comment]
@chrisjuniorli 
clear, thanks for your explain. :+1:
