### ISSUE TITLE
How to get the pretained weight     --pretrain_weights weights/r50_weight.pth 

### ISSUE THREAD

**Issue by wangbo-zhao** [wjf5203/SeqFormer#10]
I guess that the "--pretrain_weights weights/r50_weight.pth" means the weight pretained on COCO. But I can not find in you repo. Could you upload you weights? Thanks.

**Comment by chenhang98** [comment]
I found the weights here https://drive.google.com/file/d/1aWCeak2DY5arbUzYzbsAgrUfFnVkI8qi/view , 
in `Pretrain`  column of the [model zoo table](https://github.com/wjf5203/SeqFormer#youtube-vis-model).

**Comment by wangbo-zhao** [comment]
Oh thanks!

**Comment by wangbo-zhao** [comment]
> I found the weights here https://drive.google.com/file/d/1aWCeak2DY5arbUzYzbsAgrUfFnVkI8qi/view , in `Pretrain` column of the [model zoo table](https://github.com/wjf5203/SeqFormer#youtube-vis-model).
Oh Thanks!!
