### ISSUE TITLE
About GPU RAM requirements

### ISSUE THREAD

**Issue by wenhe-jia** [wjf5203/SeqFormer#11]
Not an issue, just asking about hardware requirements.

I am following you job to do VIS researching. But it came out with some limitation on GPU memory.
First, I run the **SeqFormer/models/ops/test.py** but after seconds the GPU memory is used out.
![截屏2022-01-14 15 31 55](https://user-images.githubusercontent.com/17867054/149468714-9579d7dc-9eb6-4680-b3bc-045e6a8c7db5.png)
Then, I run the **inference.py**, everything went well at the beginning, when processing the 295th video, the GPU memory was used out again.
My machine is NVIDIA TITAN xp, can you tell me how much GPU RAM is required during inference time and running **SeqFormer/models/ops/test.py**?

**Comment by wjf5203** [comment]
Thanks for your attention.
Running SeqFormer/models/ops/test.py is not necessary.
During inference,  around 15GB GPU RAM is required for ResNet-50 backbone.
