### ISSUE TITLE
Hi, can you please realese the remained pretrained weights of Swin Transformer?

### ISSUE THREAD

**Issue by xiaocc612** [wjf5203/SeqFormer#14]
It seems the pretrianed weights of Swin variants ['swin_t_p4w7', 'swin_s_p4w7', 'swin_b_p4w7', 'swin_l_p4w7', 'swin_l_p4w12'] is not provided, can you kindly realse these pretrained weights ? Thanks. : )

**Comment by wjf5203** [comment]
Hi, thanks for your attention.
We have provided 'swin_l_p4w12' model pretrained on coco in our model zoo.
For more pretrained Swin models, you can directly download weights from  https://github.com/microsoft/Swin-Transformer.
