### ISSUE TITLE
OOM when training SeqFormer_swin_L on YouTube-VIS 2019 and COCO

### ISSUE THREAD

**Issue by JiaDingCN** [wjf5203/SeqFormer#2]
Hi, thank you for your interesting work! I was trying to run your code but I meet OOM when training SeqFormer_swin_L on YouTube-VIS 2019 and COCO by your given script and command. I use 2 nodes and each node contains 8 V100 cards.  Did I do something wrong?

**Comment by jiangzhengkai** [comment]
@wjf5203 meet the same problem

**Comment by wjf5203** [comment]
The scales and max_size here should be set to [288, 320, 352, 392, 416] and 640 for swin_L backbone.
https://github.com/wjf5203/SeqFormer/blob/edbfba4503d69b351b111906336498ef9dbce70c/datasets/ytvos.py#L208
