### ISSUE TITLE
GPU memory requirements

### ISSUE THREAD

**Issue by andreaazzini** [wjf5203/SeqFormer#3]
Not an issue, more of a question: what are the GPU memory requirements of this model?

Thank you 🙂

**Comment by wjf5203** [comment]
Thanks for your attention.

**Comment by wjf5203** [comment]
Thanks for your attention.
For the ResNet50 backbone, when batchsize=2, you need almost 32G of GPU memory.
For ResNext and Swin-L backbones, the batchsize needs to be set to 1.

**Comment by andreaazzini** [comment]
Thanks, closing!
