### ISSUE TITLE
format issue of the released r50 model weight

### ISSUE THREAD

**Issue by shepnerd** [wjf5203/SeqFormer#6]
Impressive work on VIS. I met problems in evaluating phase. Any ideas are welcome.

It seems the released [r50 pretrained model](https://drive.google.com/file/d/1ecKUrt9vNZscI4gaGCrvjRLu6rDM9wNX/view?usp=sharing) cannot be directly used to evaluate YVIS dataset, since its class head may be trained on coco.
![seq-issue1](https://user-images.githubusercontent.com/5066504/147120418-8265e6a8-35ff-4561-83eb-fe7385e3bfd2.png)

After aligning the class head output dimensionality of the model to the released one, it seems inference still has one issue. I am not sure how to configure the code to address it.
![seq-issue2](https://user-images.githubusercontent.com/5066504/147120781-d0d9a0c2-b99f-47a8-b670-dee6c34cd9ff.png)

**Comment by shepnerd** [comment]
The released model works fine. The mentioned issue was caused by loading the wrong model.

**Comment by doublemanyu** [comment]
> The released model works fine. The mentioned issue was caused by loading the wrong model.
Which model do you use? Is it seqformer_r50_joint.pth?
